import { useEffect, useRef, useState, useCallback } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { toast } from "sonner";

// types.ts is auto-generated by the Supabase CLI and can lag a hand-written
// migration by a few minutes; cast where the newly added table/RPC are used
// to keep this hook resilient regardless of when types are regenerated.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabase as any;

export interface ChatMessage {
  id: string;
  listing_id: string;
  sender_id: string;
  recipient_id: string;
  body: string;
  created_at: string;
  read_at: string | null;
}

export type PhoneRevealStatus = "none" | "pending" | "approved" | "denied";

/**
 * Real-time buyer <-> seller chat thread for a single listing.
 * `partnerId` is the "other side" of the conversation (the seller/agent when
 * the current user is a buyer, or the buyer when the current user is the
 * listing owner/agent).
 */
export function useChatThread(listingId: string | undefined, partnerId: string | undefined) {
  const { user } = useAuth();
  const qc = useQueryClient();
  const queryKey = ["chat-thread", listingId, user?.id, partnerId];
  const [typing, setTyping] = useState(false);
  const typingChannelRef = useRef<ReturnType<typeof supabase.channel> | null>(null);
  const typingTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const enabled = !!listingId && !!user?.id && !!partnerId;

  const { data: messages = [], isLoading } = useQuery({
    queryKey,
    enabled,
    queryFn: async () => {
      const { data, error } = await db
        .from("messages")
        .select("*")
        .eq("listing_id", listingId)
        .or(
          `and(sender_id.eq.${user!.id},recipient_id.eq.${partnerId}),and(sender_id.eq.${partnerId},recipient_id.eq.${user!.id})`,
        )
        .order("created_at", { ascending: true });
      if (error) throw error;
      return (data ?? []) as ChatMessage[];
    },
  });

  // Realtime: new messages + read-receipt updates for this listing.
  // RLS still applies to the underlying rows delivered over the socket, so
  // filtering only by listing_id here is safe.
  useEffect(() => {
    if (!enabled) return;
    const channel = supabase
      .channel(`messages-listing-${listingId}`)
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "messages", filter: `listing_id=eq.${listingId}` },
        (payload) => {
          const row = (payload.new ?? payload.old) as ChatMessage;
          const involvesPartner = row.sender_id === partnerId || row.recipient_id === partnerId;
          if (!involvesPartner) return;
          qc.invalidateQueries({ queryKey });
        },
      )
      .subscribe();
    return () => {
      supabase.removeChannel(channel);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [listingId, partnerId, enabled]);

  // Ephemeral typing-indicator channel (broadcast only, nothing persisted).
  useEffect(() => {
    if (!enabled) return;
    const channel = supabase.channel(`typing-listing-${listingId}`, {
      config: { broadcast: { self: false } },
    });
    channel
      .on("broadcast", { event: "typing" }, (payload) => {
        if (payload.payload?.userId !== partnerId) return;
        setTyping(true);
        if (typingTimeoutRef.current) clearTimeout(typingTimeoutRef.current);
        typingTimeoutRef.current = setTimeout(() => setTyping(false), 2500);
      })
      .subscribe();
    typingChannelRef.current = channel;
    return () => {
      supabase.removeChannel(channel);
      typingChannelRef.current = null;
      if (typingTimeoutRef.current) clearTimeout(typingTimeoutRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [listingId, partnerId, enabled]);

  const broadcastTyping = useCallback(() => {
    if (!user?.id) return;
    typingChannelRef.current?.send({ type: "broadcast", event: "typing", payload: { userId: user.id } });
  }, [user?.id]);

  // Mark unread messages from the partner as read while the thread is open.
  useEffect(() => {
    if (!enabled) return;
    const unread = messages.filter((m) => m.recipient_id === user!.id && m.sender_id === partnerId && !m.read_at);
    if (unread.length === 0) return;
    (async () => {
      const { error } = await db
        .from("messages")
        .update({ read_at: new Date().toISOString() })
        .in("id", unread.map((m) => m.id));
      if (!error) qc.invalidateQueries({ queryKey });
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages, enabled]);

  const send = useCallback(
    async (body: string) => {
      if (!user?.id || !listingId || !partnerId) return;
      const trimmed = body.trim();
      if (!trimmed) return;
      const { error } = await db.from("messages").insert({
        listing_id: listingId,
        sender_id: user.id,
        recipient_id: partnerId,
        body: trimmed,
      });
      if (error) {
        toast.error(error.message || "Message failed to send");
        return;
      }
      qc.invalidateQueries({ queryKey });
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [user?.id, listingId, partnerId],
  );

  return { messages, isLoading, typing, send, broadcastTyping };
}

/** Buyer-side: request/track admin approval to reveal the seller's phone number. */
export function usePhoneReveal(listingId: string | undefined, sellerId: string | undefined) {
  const { user } = useAuth();
  const qc = useQueryClient();
  const queryKey = ["phone-reveal", listingId, user?.id];
  const enabled = !!listingId && !!user?.id && !!sellerId;

  const { data, isLoading } = useQuery({
    queryKey,
    enabled,
    queryFn: async () => {
      const { data: reqRow, error } = await db
        .from("phone_reveal_requests")
        .select("status")
        .eq("listing_id", listingId)
        .eq("buyer_id", user!.id)
        .maybeSingle();
      if (error) throw error;
      const status: PhoneRevealStatus = (reqRow?.status as PhoneRevealStatus) ?? "none";
      let phone: string | null = null;
      if (status === "approved") {
        const { data: phoneData } = await db.rpc("get_revealed_seller_phone", { p_listing_id: listingId });
        phone = phoneData ?? null;
      }
      return { status, phone };
    },
  });

  const requestReveal = useCallback(async () => {
    if (!user?.id || !listingId || !sellerId) return;
    const { error } = await db.from("phone_reveal_requests").insert({
      listing_id: listingId,
      buyer_id: user.id,
      seller_id: sellerId,
    });
    if (error) {
      toast.error(error.message || "Could not send request");
      return;
    }
    toast.success("Request sent to New Guard admin for approval");
    qc.invalidateQueries({ queryKey });
  }, [user?.id, listingId, sellerId]); // eslint-disable-line react-hooks/exhaustive-deps

  return {
    status: data?.status ?? "none",
    phone: data?.phone ?? null,
    isLoading,
    requestReveal,
  };
}
